config:
  backup: true
  banner: true
  create: true
  dotpath: files
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop/
  link_on_import: link
  minversion: 1.6.0
dotfiles:
  f_bash_logout:
    dst: ~/.bash_logout
    link: link
    src: bash_logout
  f_bash_profile:
    dst: ~/.bash_profile
    link: link
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    link: link
    src: bashrc
  f_dircolors:
    dst: ~/.dircolors
    link: link
    src: dircolors
profiles:
  ngenetzky-skull:
    dotfiles:
    - f_bash_logout
    - f_bash_profile
    - f_bashrc
    - f_dircolors
  yoga:
    dotfiles:
    - f_bash_logout
    - f_bash_profile
    - f_bashrc
    - f_dircolors
